# 🕵️ AI Investigator Copilot

## Overview

The AI Investigator Copilot is a prototype application demonstrating how AI can support Financial Crime investigators by enriching transaction monitoring alerts, explaining risk drivers and recommending investigative actions.

The solution acts as an intelligence layer above existing Financial Crime platforms, helping investigators understand alerts more quickly and consistently while keeping human decision-making and regulatory accountability at the centre of the process.

---

## Business Problem

Financial Crime investigators often review large volumes of alerts generated by Transaction Monitoring systems.

Investigators typically gather information from multiple sources, including:

- Transaction Monitoring platforms
- Customer Risk Assessments
- KYC repositories
- Adverse Media systems
- Network Analytics platforms
- Case Management solutions

This process can be manual, time-consuming and inconsistent.

---

## Prototype Objective

The objective of this prototype is to demonstrate how AI can:

- Summarise alerts
- Explain risk drivers
- Prioritise investigations
- Recommend next investigative actions
- Support case documentation
- Improve investigator productivity

---

## Current Functionality

### Alert Summary

Provides a concise overview of the alert, including:

- Customer
- Risk Score
- Alert Priority
- Counterparty Information

### Risk Driver Explanation

Identifies key factors contributing to alert risk, including:

- High-risk jurisdictions
- Transaction value anomalies
- New counterparties
- Adverse media indicators
- Network relationship risks

### Recommended Investigator Actions

Provides contextual guidance, including:

- KYC review
- Commercial rationale assessment
- Enhanced Due Diligence
- Escalation recommendations

---

## Example Workflow

```text
Transaction Monitoring Alert
            ↓
      Risk Scoring
            ↓
      AI Enrichment
            ↓
 Risk Driver Explanation
            ↓
 Investigator Guidance
            ↓
 Draft Case Narrative
            ↓
 Investigator Decision

 ## Disclaimer

This prototype is intended for demonstration and educational purposes only. It is not intended for production use and should not replace investigator judgement, regulatory controls or existing Financial Crime governance processes.
