# 🕵️ AI Investigator Copilot

## Overview

The AI Investigator Copilot is a prototype application demonstrating how AI can support Financial Crime investigators by enriching transaction monitoring alerts, explaining risk drivers and recommending investigative actions.

The solution acts as an intelligence layer above existing Financial Crime platforms, helping investigators understand alerts more quickly and consistently while keeping human decision-making and regulatory accountability at the centre of the process.

---

## Business Problem

Financial Crime investigators often review large volumes of alerts generated by Transaction Monitoring systems.

Investigators typically gather information from multiple sources, including:

- Transaction Monitoring platforms
- Customer Risk Assessments
- KYC repositories
- Adverse Media systems
- Network Analytics platforms
- Case Management solutions

This process can be manual, time-consuming and inconsistent.

---

## Prototype Objective

The objective of this prototype is to demonstrate how AI can:

- Summarise alerts
- Explain risk drivers
- Prioritise investigations
- Recommend next investigative actions
- Support case documentation
- Improve investigator productivity

---

## Current Functionality

### Alert Summary

Provides a concise overview of the alert, including:

- Customer
- Risk Score
- Alert Priority
- Counterparty Information

### Risk Driver Explanation

Identifies key factors contributing to alert risk, including:

- High-risk jurisdictions
- Transaction value anomalies
- New counterparties
- Adverse media indicators
- Network relationship risks

### Recommended Investigator Actions

Provides contextual guidance, including:

- KYC review
- Commercial rationale assessment
- Enhanced Due Diligence
- Escalation recommendations

---

## Example Workflow

Transaction Monitoring Alert
            ↓
      Risk Scoring
            ↓
      AI Enrichment
            ↓
 Risk Driver Explanation
            ↓
 Investigator Guidance
            ↓
 Draft Case Narrative
            ↓
 Investigator Decision


## Future Roadmap
The current prototype demonstrates Versions 1–2 of the AI Investigator Copilot vision. The roadmap below outlines the planned evolution toward a fully AI-enabled Financial Crime investigation platform.

## Potential version 2?
Version 2 - Connect to an actual LLM
Every alert would generate a different commentary.

Alert
  ↓
Risk Engine
  ↓
Prompt Builder
  ↓
GPT / OpenAI / Internal bank LLM
  ↓
AI Narrative
  ↓
Investigator Dashboard

## Potential version 3?
Version 3 - Converstaional copilot capability
Copilot recommends actions

Alert
 ↓
Risk Score
 ↓
AI Copilot
 ↓
Ask Questions


 # | Version | Capability | Functionality Upgrade | Status |
|---|---------|------------|----------------------|--------|
| 1 | V1 | Risk Scoring Prototype | Rules-based risk scoring using customer, transaction, geography, counterparty and adverse media indicators | Complete |
| 2 | V2 | AI Enrichment & Narrative Generation | Generates risk explanations, investigator commentary, recommended actions and draft case narratives from alert data | Complete |
| 3 | V3 | Investigator Copilot Dashboard | Interactive operational dashboard presenting alert summaries, risk drivers, recommendations and investigator outputs | In Development |
| 4 | V4 | Dynamic Prompt Engineering | Automatically builds tailored prompts based on alert typology such as sanctions, adverse media, network risk or transaction anomalies | Planned |
| 5 | V5 | Multi-Risk Context Reasoning | Combines multiple risk factors into a prioritised assessment and explains which risks are most material to the investigation | Planned |
| 6 | V6 | Agentic Financial Crime Investigator | AI determines additional information required, gathers evidence and produces investigative recommendations autonomously | Planned |
| 7 | V7 | Conversational Investigator Assistant | Investigators interact with alerts using natural language questions and receive contextual responses from the copilot | Planned |
| 8 | V8 | SAR Drafting Copilot | Generates Suspicious Activity Report narratives using alert data, investigator decisions and supporting evidence | Planned |
| 9 | V9 | Investigation Workflow Orchestration | Guides investigators through review procedures, controls, escalation paths and policy requirements | Planned |
| 10 | V10 | Knowledge & Typology Intelligence Layer | Integrates typology libraries, historical investigations and institutional knowledge into the copilot workflow | Planned |
| 11 | V11 | Network Analytics Integration | Incorporates entity resolution, beneficial ownership, hidden relationships and network intelligence into investigations | Planned |
| 12 | V12 | Trade Finance & TBML Copilot | Applies AI-driven reasoning and enrichment to Trade Finance and Trade-Based Money Laundering investigations | Planned |
| 13 | V13 | Correspondent Banking Analytics Copilot | Provides contextual analysis of payment flows, sanctions exposure and nested banking relationships | Planned |
| 14 | V14 | Capital Markets Surveillance Copilot | Supports market abuse, insider dealing and surveillance investigations through AI-assisted analysis | Planned |
| 15 | V15 | Enterprise Financial Crime AI Platform | Unified AI operating model covering AML, KYC, Fraud, Network Analytics, Surveillance and Regulatory Reporting | Vision |


